### ISSUE TITLE
Minimized DFA not minimal

### ISSUE THREAD

**Issue by almullay** [whitemech/pythomata#112]
**Describe the bug**
Minimized DFA does not appear to be minimal.

**To Reproduce**
To reproduce, run conv_rust2pyth_min.py in [test.zip](https://github.com/whitemech/pythomata/files/6871334/test.zip). Observe that the output DFA (rendered in test.svg in the zip file) has a cluster of trivial accept states below state 9.

**Expected behavior**
Expected to obtain the unique minimal DFA recognizing the same language, but looking at the DFA in test.svg, we could add self-loops for all characters to state 9, remove all other accepting states below, and decide the same language.

**Screenshots**
The DFA is too large to screenshot well. Please see test.svg in the zip file above.
![image](https://user-images.githubusercontent.com/23005591/126845331-31e8c44d-dd8e-42ad-a749-4bfabf5bba1f.png)

**Comment by marcofavorito** [comment]
Hi @almullay,

thank you for your interest in the library.

I have some comments on your issues.

> Observe that the output DFA (rendered in test.svg in the zip file) has a cluster of unreachable DFA states below state 9.

Why do you think they are unreachable? Take any path from the initial state to state 9; then, you can read 'a' to reach state 35, and read 'c' to reach state 14. Apply the same reasoning recursively, and you can see you can reach also the other states.

>  Expected to obtain the unique minimal DFA recognizing the same language, but looking at the DFA in test.svg, we could add self-loops for all characters to state 9, remove all other accepting states below, and decide the same language.

If you add self-loops for all characters to state 9, you don't accept the same language of the automaton you have specified. The reason is: consider any word `w` that reaches state 9 for the first time. If you add self-loop, you will accept any extension of the word `w`. Instead, look at `test.svg`. If the automaton reads "b", it fails. 

The same reasoning can be applied to the other accepting states; there is always a character that can make the execution to fail. You can see this by rendering the `complete()` automaton.

**Comment by almullay** [comment]
Forgive me, I did not realize that the DFA was incomplete. Feel free to remove this false issue. Thank you @marcofavorito.
